### PR TITLE
Redesign field properties to work with nested structure

### LINKED ISSUE #7: Unexpected value when deserializing into array of optional elements
When deserializing into an array with Option type with multiple elements, including tuples or multi-field structs. If `None` value visited, the deserialized result will skip extra fields.

For example:

```rust
let s = " 222 111         253 254 121 232";
let mut fields = vec![];
for i in 0..8 {
    fields.push(Field::default().range(i * 4..i * 4 + 4))
}

let arr: [Option<(u8, u8)>; 4] = fixed_width::from_str_with_fields(s, fields.clone()).unwrap();
for p in arr.iter() {
    println!("{:?}", p);
}
```

expected:

```rust
Some((222, 111))
None
Some((253, 254))
Some((121, 232))
```

got:

```rust
Some((222, 111))
None
None
Some((253, 254))
```

BTW, elements with single field will just works as expected.

```rust
let arr: [Option<u8>; 8] = fixed_width::from_str_with_fields(s, fields.clone()).unwrap();
for p in arr.iter() {
    println!("{:?}", p);
}
```

got:

```rust
Some(222)
Some(111)
None
None
Some(253)
Some(254)
Some(121)
Some(232)
```

### PR DESCRIPTION
**Pull request by ongchi**
Fixes #7

### CODE REVIEW

File: fixed_width/src/de.rs [hunk 1]
```diff
@@ -488,29 +485,17 @@ impl<'a, 'de: 'a> serde::Deserializer<'de> for &'a mut Deserializer<'de> {
...
-        } else if let Ok(n) = s.parse::<i64>() {
-            visitor.visit_i64(n)
-        } else if let Ok(n) = s.parse::<f64>() {
-            visitor.visit_f64(n)
-        } else {
-            visitor.visit_str(&s)
-        }
+    // FixedWidth is not self describing format should avoid this method.
+    fn deserialize_any<V: Visitor<'de>>(self, _visitor: V) -> Result<V::Value, Self::Error> {
+        Err(DeserializeError::WontImplement)
```
Comment (twking7) [inline fixed_width/src/de.rs:498]: I agree this method probably doesn't make a ton of sense for a non self describing format, what do you think about deserializing to a string if the user asks for an Any?

File: fixed_width/src/de.rs [hunk 2]
```diff
@@ -521,10 +506,13 @@ impl<'a, 'de: 'a> de::SeqAccess<'de> for &'a mut Deserializer<'de> {
...
-            Ok(None)
-        } else {
-            seed.deserialize(&mut **self).map(Some)
+        match self.fields.peek() {
+            Some(FieldSet::Item(_)) => seed.deserialize(&mut **self).map(Some),
+            Some(FieldSet::Seq(_)) => {
+                let mut de = Deserializer::new(self.input, self.fields.next().unwrap());
+                seed.deserialize(&mut de).map(Some)
+            }
+            None => Ok(None),
```
Comment (twking7) [inline fixed_width/src/de.rs:515]: Nice!

File: fixed_width/src/de.rs (hunk 1 above)
Comment (ongchi) [reply fixed_width/src/de.rs:498]: There are no ways to infer the type at runtime as I know.
I think most people use derive macro to implement `Deserialize` and `Visitor` trait automatically, and the `Visitor` will forward `Deserializer` to a specific method by the type signature. Also the same story when implementing required traits manually. The format specifications for fixed-width should determine at compile-time rather than at runtime, and it's the only way to go. If the target type signature is `String`, just pass the `Deserializer` to `deserialize_string` but not `deserialize_any`. For more specific usage, people probably should go with field attribute (`#[serde(deserialize_with = "path")]`) to specify their `Deserializer` for that case.

Comment (twking7) [reply fixed_width/src/de.rs:498]: Fair enough. FWIW, when I originally wrote this I took inspiration from the serde implementation from csv (which ultimately calls this function): https://github.com/BurntSushi/rust-csv/blob/master/src/deserializer.rs#L206

**Comment by ongchi** [comment]
I just realized it's a bit messy to put complex syntax into procedural macro and might not be a good choice. The current macro is nice and clear for simple cases, adding support for nested fields definition seems too verbose for lengthy fields, maybe I should just implement a container attribute letting user specify their complex fields by a custom function. ex:

```rust
#[derive(FixedWidth, Deserialize)]
#[fixed_width(field_def="custom_function")]
struct Foo {
    ...
}
```

Which is identically with implement the `FixedWidth` trait manually but more like serde api, or just leave it untouched.
What do you think?

File: fixed_width/src/de.rs (hunk 1 above)
Comment (ongchi) [reply fixed_width/src/de.rs:498]: Took some time to figure out rust-csv, I could be wrong, but just leave a note.
The `deserialize_any` is called by `EnumAccess` to determine its variant in `rust-cvs`.
The cvs format is created by hands or machine generated, may contains unexpected values in a column in my experience, so I can understand why the value would pass to `deserialize_any`, but implement global enum maybe a better choice (like [serde_json::value::Value](https://docs.serde.rs/serde_json/value/enum.Value.html)), but also, may be too heavy for that case.
For `fixed_width`, my use case is parsing data generated from fortran fixed format output, its machine generated contents, guarantee typed, and everything should known at compile-time.

**Comment by twking7** [comment]
@ongchi I think that makes sense!

**Comment by ongchi** [comment]
> I just realized it's a bit messy to put complex syntax into procedural macro and might not be a good choice. The current macro is nice and clear for simple cases, adding support for nested fields definition seems too verbose for lengthy fields, maybe I should just implement a container attribute letting user specify their complex fields by a custom function. ex:
> 
> ```rust
> #[derive(FixedWidth, Deserialize)]
> #[fixed_width(field_def="custom_function")]
> struct Foo {
>     ...
> }
> ```
> 
> Which is identically with implement the `FixedWidth` trait manually but more like serde api, or just leave it untouched. What do you think?

Maybe someday will get this done

**Comment by ongchi** [comment]
Document updated. Everything should works properly.

**Comment by twking7** [comment]
Thank you! I will check this out asap - been busy with some IRL stuff.

File: README.md [hunk 3]
```diff
@@ -1,17 +1,19 @@
...
 
-Fixed width in this case means that each line of the file is the same number of bytes. It supports unicode, but only if the unicode fits in the designated byte size of the record.
-
-## Documentation
-
-https://docs.rs/fixed_width
+Fixed width in this case means that each line of the file is the same number of bytes.
+It supports unicode, but only if the unicode fits in the designated byte size of the record.
+It also provides a few useful abstractions to ease serializing and deserializing data into and out
+of fixed width files.
```
Comment (twking7) [inline README.md:16]: 👍

**Review by twking7 — APPROVED** [review]
Thank you for contributing this! It looks great. I'll merge this and push the new version.
